#!/usr/bin/env bash
# Script that automatically configures an Ubuntu machine that has a status:
# 301 Moved Permanently

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo echo "Hello World!" > /etc/nginx/html/index.html
sudo printf %s "server {
     listen	 80 default_server;
     listen	 [::]:80 default_server;
     root	 /etc/nginx/html;
     index	 index.html index.htm;
     location /redirect_me {
          return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
     }
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
