#!/usr/bin/env bash
# Script that configures a new UBuntu machine for installing and configuring HAproxy.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  smartcodez-frontend
        bind *:80
        mode http
        default_backend smartcodez-backend
backend smartcodez-backend
        balance roundrobin
        server 52736-web-01 52.91.154.135:80 check
        server 52736-web-02 54.87.207.246:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
