#!/usr/bin/env bash
# Script that configures a new UBuntu machine for installing and configuring HAproxy.

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy=2.0.\*
sudo apt update && sudo apt upgrade -y
servers=\
"
frontend ibangajnr-frontend
	bind *:80
	mode http
	default_backend ibangajnr-backend
backend ibangajnr-backend
	balance roundrobin
	server 127622-web-01 54.83.131.175 check
	server 127622-web-02 54.144.21.80 check
"
echo "$servers" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
