#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it.
sudo mysqldump --all-databases -u root --password="$1" > backup.sql
sudo ar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
