#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump --all-databases -u root --password="$1" > backup.sql | gzip > `date +\%d-\%m-\%y`.tar.gz
