#!/usr/bin/env bash
# Fix the bug to allow nginx to listen on port 80 
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
kill "$(pgrep 'nginx' | head -1)"
