#!/usr/bin/env bash
# Displays the content of the file /etc/passwd.
# Only username,  user id and HOme directory path for the user
while read passwd; do
	echo "$passwd" | cut -d ':' -f1,3,6
done < /etc/passwd
