#!/usr/bin/env bash
# Loops from 1 to 10 and:
# Displays bad luck for the 4th loop iteration
# Displays good luck for the 8th loop iteration
# Displays Best School for the other iterations
count=1
while [ $count -lt 11 ];
do
	if [ $count -eq 4 ];
	then
		echo "bad luck"	
	elif [ $count -eq 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
