#!/usr/bin/env bash
# Gives you information about the school file.
fileName="./school"
if [ -e "$fileName" ]
then
	echo "school file exists"
	if [ ! -s "$fileName" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	
	if [ -f "$fileName" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
